// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUFoTzBUVjl4RTBHVlVVdW5IRWlDY016YTMwSmlvL0NEMWx2Wi81dzlHdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSFNFa3VEUFJzOHdxSFBGZmdyeURkdW0zZDFRUFhYUi9EZW5ZMWhibkRqND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlTTFVbjFhd0djWTByZ25Jb3hKUW5TRHdiRC9tTDVCZ2lkdHNVMCtzclZZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCOGpWaGo4anJ0NzhqUDlqVHJTL3VWcVNvbTUzZkNsOHFjYkx2SzVGakc4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktINEVsandGd1kyR0tBOHBwM0pQbGcxVTZJaWcrVUtRRnhCNWYyRnZPM0U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkxEYUFYTEtTK1BNOWEzSWxVRjB5Z3llaGJWZjBHVWdGb2JCbyt2a1ZUQ2M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0V6aEhsclowZGlpK1ZCL0ZSV3ZYaHh4TzRvenRkY3BvYWQ3ZTBoVnJrTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRFBLOUYvMW1jZnRscC9aa2dHRS9SY2V4M09rQlZFTTVzcGZ6UUJyeS9qRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlRhcVBjWVg2NFdJU3hxOVNLVHVFbFVYYlpsZEhpVUtSOWUxMHc3Mm5xeEpvNHRmWXVTQzVrekEzU1dOVldnUGltOEtkb0JoSTFtOVlWaUNwN0Z4R2lBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTUsImFkdlNlY3JldEtleSI6IjNJZWJ6UDlWKzJuSGR6SWo1WTFkVmRZUnhqYmk4OXhvT1U0ajNoNGJtcE09IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MDEwNzMwMzdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOEY1QkE0OEFFQjA1NEE4MzRDRjkzOUY5NTY2RjJCMjcifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMDYyNzI3MX0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MDEwNzMwMzdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRjdGRDBGODBENkZCMDVDMDIyQzkzNzhBRDlCQkNBOTQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMDYyNzI3MX1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiYVBockVfTmJUZWk5MW82SkhJQzBtZyIsInBob25lSWQiOiI0ZDExOTNiYy02ZDhhLTQ5NzUtYWQxMy1jMzFhMGVjYjI1YzQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYnpMSVJjQ0g0R1VFcXI1TlJjRHNjZXpRRnhjPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkMzYWVMRlZjNEZlbDFLNlZmZ3JjYXY1QzJlQT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiIzMllNNTdGNSIsIm1lIjp7ImlkIjoiOTQ3MDEwNzMwMzc6MjZAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiUFJPSkVDVCA0MDQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0puVzY2a0ZFTGJndXJRR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlFRQTlZa3BvU3krd0dabjd6RjVOVG1JM0FLbnpWVEZpZTRlZ0xBSlBNVzg9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImJrdktRWC9VbUc5TWtPdUp4eUdiSEc4dmN0b29uUTJ1dXRFUHZ1U05nWk8waU1OVXl0YWU2a0EwTVNXVkdCS0ZCV21IVlBHUUhzWk5Ea1JKR3h3SkNnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIrZVJtTGJrZExlTWw5Wjl0V2ZiYXkwUVBya3lIS2FEWHBvK1o2VzRPaGZRcjlXZEZ0Uk5WanZMOGRIWTF4c0N5WVdCUDdzZ2hXNnduaHdOR25CL2dqUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6Ijk0NzAxMDczMDM3OjI2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlVFQVBXSkthRXN2c0JtWis4eGVUVTVpTndDcDgxVXhZbnVIb0N3Q1R6RnYifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjA2MjcyNjksIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRzBEIn0=",
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "MIHIRUK DILSHAN",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "94778764083",
  GEMINI_KEY: process.env.GEMINI_KEY || "",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
